#include "room.h"
#include "user.h"

int docommand(user *currentuser,char *s);
int north_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int south_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int east_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int west_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int northwest_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int southwest_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int southeast_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int northeast_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int up_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int down_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int look_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int who_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int say_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int whisper_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int pose_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int home_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int quit_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int version_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int describe_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int get_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int drop_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int help_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int password_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int cast_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int fight_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int score_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int inv_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int give_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int xyzzy_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int setrace_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int set_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int sethome_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int setgender_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int setlevel_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int setclass_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int setxp_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int setmp_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int setsp_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int banip_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int unban_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int ban_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int kill_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int create_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int delete_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int rename_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int chown_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);		/* set object owner */
int chmod_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int copy_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int move_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int dig_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int force_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int listban_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int go_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int wall_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int take_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int reload_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int shutdown_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int addclass_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int addrace_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int dropdead_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int invisible_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int visible_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int gag_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int ungag_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);
int setexit_command(user *currentuser,int tc,char *command_tokens[BUF_SIZE][BUF_SIZE]);


