int UpdateRoomInDatabase(user *user,int room);
int UpdateObjectInDatabase(user *currentuser,roomobject *roomobject);
int LoadWorld(void);
int LoadWorldObjects(void);
int SetExit(user *currentuser,int whichroom,char *setexitdirection,int targetroom);
int CreateRoom(user *currentuser,char *roomdirection);
int SetObjectAttributes(user *currentuser,unsigned int ObjectID,int attributes);
int SetOwner(user *currentuser,unsigned int ObjectID,char *owner);
int CopyObject(user *currentuser,unsigned int ObjectID,int DestinationRoom);
int GenerateObjects(void);
int CreateObject(user *currentuser,roomobject *object,int room);
int DeleteObject(user *currentuser,unsigned int ObjectID);
int RenameObject(user *currentuser,unsigned int ObjectID,char *newname);
int CopyFile(char *source,char *destination);
int SetObjectDescription(user *currentuser,unsigned int ObjectID,char *description);
char *GetDirectionName(int direction);
char *GetRoomName(int RoomNumber);
room *GetRoomPointer(int RoomNumber);
int GetRoomExit(int RoomNumber,int direction);
int GetRoomAttributes(int RoomNumber);
void SetFirstMonsterInRoom(int RoomNumber,monster *Monster);
int IsObjectInRoom(char *name,int RoomNumber);
int GetNumberOfRooms(void);
unsigned int GetNextObjectNumber(void);
int SetRoomDescription(user *currentuser,int RoomNumber,char *description);
int AddMonsterToRoom(monster *sourcemonster,int RoomNumber);
monster *FindFirstMonsterInRoom(int RoomNumber);
monster *FindNextMonsterInRoom(monster *previous);
void SetNumberOfMonstersInRoom(int RoomNumber,int NumberOfMonsters);
int GetNumberOfMonstersInRoom(int RoomNumber);
int DoObjectVerbAction(user *currentuser,char *verb,char *ObjectName);

