port=5000
BackupDatabase=true
AllowPlayerKilling=true
AllowNewAccounts=true
MaximumNumberOfObjectsPerRoom=5
MonsterGenerateTime=30m
ObjectGenerateTime=20m
PointsForHero=800
PointsForWarrior=400
PointsForChampion=1600
PointsForSuperhero=3200
PointsForEnchanter=6400
PointsForSorceror=128000
PointsForNecromancer=256000
PointsForLegend=512000
PointsForWizard=1024000
